services:

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: teknofest
      POSTGRES_USER: teknofest
      POSTGRES_PASSWORD: teknofest

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  teknofest-backend:
    image: jahangiraze/teknofest-backend:latest

    depends_on:
      - postgres

    ports:
      - "8080:8080"

    env_file:
      - .env

volumes:
  postgres_data:
  redis_data:
