spring:
  application:
    name: teknofest

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${NO_REPLY_EMAIL}
    password: ${NO_REPLY_EMAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${PORT:8080}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-token:
        expiration: ${ACCESS_TOKEN_EXPIRATION}
      refresh-token:
        expiration: ${REFRESH_TOKEN_EXPIRATION}

  frontend:
    base-url: ${FRONTEND_BASE_URL:http://localhost:5173}
