spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/teknofest}
    username: ${DB_USERNAME:teknofest}
    password: ${DB_PASSWORD:teknofest}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
