spring:
  application:
    name: teknofest

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml

server:
  port: ${PORT:8080}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
